version: "2"
services:
  awhdispergodb:
    build: ./awhdispergodb
    environment:
      DB_NAME: awhdispergodb 
      USERNAME: superman
      PASSWORD: kryptonite
      ALLOCMEMMB: 500
    volumes:
      - ./dispergodata:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - dispergodb
  awhdispergosync:
    build: ./awhdispergosync
    depends_on:
      - awhdispergodb 
    ports:
      - 4984:4984
    networks:
      - dispergodb
networks:
  dispergodb:
    driver: bridge
